### ISSUE TITLE
Self evaluation doesn't work for my model card

### ISSUE THREAD

**Issue by mory91** [huggingface/audio-transformers-course#114]
Seems like there's a problem with the code for self evaluation. I've completed the unit 4 hands on task but self evaluation doesn't count it as succesful. I took a look at the code and it seem's like my model card outputs the accuracy as eval_accuracy instead of Accuracy. Am I doing something wrong or the model card pattern has been changed and the self evaluation script is not yet updated?

**Comment by MKhalusova** [comment]
Can you share a link to your model here, please?

**Comment by mory91** [comment]
This is the model:

https://huggingface.co/mory91/distilhubert-finetuned-gtzan

**Comment by MKhalusova** [comment]
Thanks! I believe it's fixed now.
