### ISSUE TITLE
doc-builder error

### ISSUE THREAD

**Issue by Lightmourne** [huggingface/audio-transformers-course#118]
Hello!

I translated chapter2 into Russian. After finishing the translation, I wanted to test the correct display of the content of this chapter. For this purpose I used _doc-builder_. I ran into a problem because the files _asr_pipeline.mdx_ and _audio_classification_pipeline.mdx_ are not displayed in the browser at http://localhost:3000/. Instead I get the following message:
```
Error while preprocessing /tmp/tmpalt8krht/kit/src/routes/chapter2/asr_pipeline.mdx - btoa is not defined
```
```
ReferenceError: Error while preprocessing /tmp/tmpalt8krht/kit/src/routes/chapter2/asr_pipeline.mdx - btoa is not defined
    at base64 (file:///tmp/tmpalt8krht/kit/preprocess.js:435:28)
    at highlighter (file:///tmp/tmpalt8krht/kit/preprocess.js:488:13)
    at /tmp/tmpalt8krht/kit/node_modules/mdsvex/dist/main.cjs.js:25745:25
    at Array.map (<anonymous>)
    at /tmp/tmpalt8krht/kit/node_modules/mdsvex/dist/main.cjs.js:25743:11
    at wrapped (/tmp/tmpalt8krht/kit/node_modules/mdsvex/dist/main.cjs.js:206:19)
    at next (/tmp/tmpalt8krht/kit/node_modules/mdsvex/dist/main.cjs.js:299:28)
    at done (/tmp/tmpalt8krht/kit/node_modules/mdsvex/dist/main.cjs.js:236:16)
    at then (/tmp/tmpalt8krht/kit/node_modules/mdsvex/dist/main.cjs.js:243:5)
    at wrapped (/tmp/tmpalt8krht/kit/node_modules/mdsvex/dist/main.cjs.js:226:9)
```
I would like to note that the files _introduction.mdx_ and _hands_on.mdx_ are displayed correctly. These files do not contain blocks with python code.
How to solve this problem?

I attach a screenshot of one of the correctly displayed pages.
![Снимок экрана от 2023-08-02 13-51-31](https://github.com/huggingface/audio-transformers-course/assets/72374407/4340a30f-4309-45fe-a5ec-0f8c47543595)

**Comment by MKhalusova** [comment]
cc @mishig25 can you please take a look?

**Comment by sanchit-gandhi** [comment]
Any luck here @Lightmourne? I saw that your PR for the Russian translation of Unit 5 rendered ok with the doc-builder!

**Comment by sanchit-gandhi** [comment]
Gently pinging @mishig25

**Comment by MKhalusova** [comment]
@Lightmourne  Is this issue still relevant?

**Comment by Lightmourne** [comment]
@MKhalusova issue resolved
