### ISSUE TITLE
Update MMS section

### ISSUE THREAD

**Issue by osanseviero** [huggingface/audio-transformers-course#121]
MMS is already released in `transformers`, so https://huggingface.co/learn/audio-course/chapter6/pre-trained_models#massive-multilingual-speech-mms could be updated to use that instead

**Comment by MKhalusova** [comment]
It appears that the TTS part of MMS has not been merged yet, here's the PR that's still open https://github.com/huggingface/transformers/pull/24085

Unless it moved to a different PR that I am not aware of? cc @sanchit-gandhi

**Comment by osanseviero** [comment]
Yes, you're right. MMS was merged but the TTS Part depends on VITS getting in. Closing this in the meantime :)
