### ISSUE TITLE
Why are code and code outputs in the same code block in the text?

### ISSUE THREAD

**Issue by ritog** [huggingface/audio-transformers-course#49]
I am going through the [ Load and explore an audio dataset](https://huggingface.co/learn/audio-course/chapter1/load_and_explore) section of the tutorial.

And I saw that code and code outputs are contained in the same code block, which I believe will confuse people.

![image](https://github.com/huggingface/audio-transformers-course/assets/58001482/d07f18c2-7ca5-4de0-83df-a65b4b106d19)

I strongly belief that code and code output should go into different blocks of code, or the output may even be inserted as plaitext with monospace font, outside of a code block.

Please make this change.

If you need help, I can create PRs doing this. Let me know once you decide the style.

**Comment by MKhalusova** [comment]
Fixed :) Thanks again for pointing this out.
