### ISSUE TITLE
Step 4 jumped to step 6

### ISSUE THREAD

**Issue by fisheggg** [huggingface/audio-transformers-course#69]
In https://github.com/huggingface/audio-transformers-course/blob/main/chapters/en/chapter0/get_ready.mdx, theres a [step 6](https://github.com/huggingface/audio-transformers-course/blob/a77d4eaf0d4dfebb1662a1d363cb4d4573426e05/chapters/en/chapter0/get_ready.mdx#L32) right after [step 4](https://github.com/huggingface/audio-transformers-course/blob/a77d4eaf0d4dfebb1662a1d363cb4d4573426e05/chapters/en/chapter0/get_ready.mdx#L24).

**Comment by fisheggg** [comment]
Fixed by #63

**Comment by MKhalusova** [comment]
Thanks for the fix!
