### ISSUE TITLE
Unusual ImportError (Chapter 4, Fine-Tuning)

### ISSUE THREAD

**Issue by MHRDYN7** [huggingface/audio-transformers-course#96]
An import error is raised when the TrainingArguments() is called. 
[ImportError: Using the `Trainer` with `PyTorch` requires `accelerate>=0.20.1`: Please run `pip install transformers[torch]` or `pip install accelerate -U`]
However, this issue continues even if the latest version of Accelerate (0.21.0) is installed.
@sanchit-gandhi You can have a look at this [notebook](https://colab.research.google.com/drive/1g5_t7taWoSTbQqQba43ysKkyPLqPmVe5?usp=sharing).

**Comment by sanchit-gandhi** [comment]
Hey @MHRDYN7 - the error specifies an accelerate version of 0.20.1. Can you ensure you have this version? (and not 0.21.0 as stated in your issue). To do so, simply run:
```
pip install --upgrade accelerate
```
